import { useEffect, useState } from 'react'
import Image from 'next/image'
import { Tab } from '@headlessui/react'
import clsx from 'clsx'

import { Container } from '@/components/Container'
import backgroundImage from '@/images/background-features.jpg'
import screenshotExpenses from '@/images/screenshots/expenses.png'
import screenshotPayroll from '@/images/screenshots/payroll.png'
import screenshotReporting from '@/images/screenshots/reporting.png'
import screenshotVatReturns from '@/images/screenshots/vat-returns.png'

import generate from '@/images/generate.svg'
import lock from '@/images/lock.svg'
import relax from '@/images/relax.svg'
import revenues from '@/images/earn.svg'
import heroimg from "../images/hero.png"

//{
//  title: 'Join a Campaign',
//  description:
//    "The funds deposited on a campaign are used to generate yield through different defi protocol ",
//  image: screenshotPayroll,
//},
//{
//  title: 'Generate Revenue',
//  description:
//    "The yield generated by the TVL of a campaign is then redistributed between the IbToken owners and the campaign manager",
//  image: screenshotExpenses,
//},
//{
//  title: 'Claim Your Rewards',
//  description:
//    "You can withdraw deposited funds, as well as the income generated by them, at any time! ",
//  image: screenshotVatReturns,
//},
//{
//  title: 'Wait And Relax',
//  description:
//    'over time, income is fed back into the liquidity pool, increasing returns!',
//  image: screenshotReporting,
//},
//]
//a

const incentives = [
  {
    name: 'Join a Campaign',
    imageSrc: lock,
    description: "The funds deposited on a campaign are used to generate yield through different defi protocol",
  },
  {
    name: 'Generate Revenue',
    imageSrc: generate,
    description: "The yield generated by the TVL of a campaign is then redistributed between the IbToken owners and the campaign manager",
  },
  {
    name: 'Claim Your Rewards',
    imageSrc: revenues,
    description:
      "You can withdraw deposited funds, as well as the income generated by them, at any time!",
  },
  {
    name: 'Wait And Relax',
    imageSrc: relax,
    description:
      "Over time, income is fed back into the liquidity pool, increasing returns!",
  },
]

export function PrimaryFeatures() {
  let [tabOrientation, setTabOrientation] = useState('horizontal')

  useEffect(() => {
    let lgMediaQuery = window.matchMedia('(min-width: 1024px)')

    function onMediaQueryChange({ matches }) {
      setTabOrientation(matches ? 'vertical' : 'horizontal')
    }

    onMediaQueryChange(lgMediaQuery)
    lgMediaQuery.addEventListener('change', onMediaQueryChange)

    return () => {
      lgMediaQuery.removeEventListener('change', onMediaQueryChange)
    }
  }, [])

  return (
    <section
      id="features"
      aria-label="Features for running your books"
      className="relative overflow-hidden bg-blue-600 pt-20 pb-28 sm:py-32"
    >
      <Image
        className="absolute top-1/2 left-1/2 max-w-none translate-x-[-44%] translate-y-[-42%]"
        src={backgroundImage}
        alt=""
        width={2245}
        height={1636}
        unoptimized
      />
      <Container className="relative">
        {/* <div className="max-w-2xl md:mx-auto md:text-center xl:max-w-none">
          <h2 className="font-display text-3xl tracking-tight text-white sm:text-4xl md:text-5xl">
          Act for what matters to you
          </h2>
          <p className="mt-6 text-lg tracking-tight text-blue-100">
          Become an actor of a movements that would not exist without you
          </p>
        </div> */}

        <div className="mx-auto max-w-7xl py-4 sm:px-2 sm:py-2 lg:px-4">
          <div className="mx-auto max-w-2xl px-4 lg:max-w-none">
            <div className="grid grid-cols-1 items-center gap-y-10 gap-x-16 lg:grid-cols-2">
              <div>
                <h2 className="text-4xl font-display font-bold tracking-tight text-white">
                  Act for what matters to you              </h2>
                <p className="mt-4 tracking-tight text-gray-300">
                  Become an actor of a project that would not exist without you.
                </p>
                <p className="tracking-tight text-gray-300">
                  It is now possible to change things, with a few clicks.
                </p>
              </div>
              <div className="aspect-w-3 aspect-h-2 overflow-hidden rounded-lg bg-gray-100">
                <Image
                  src={heroimg}
                  alt=""
                  className="object-cover object-center"
                />
              </div>
            </div>
            <div className="mt-16 grid grid-cols-1 gap-y-10 gap-x-8 lg:grid-cols-4">
              {incentives.map((incentive) => (
                <div key={incentive.name} className="sm:flex lg:block">
                  <div className="sm:flex-shrink-0">
                    <Image className="h-16 w-16" src={incentive.imageSrc} alt="" />
                  </div>
                  <div className="mt-4 sm:mt-0 sm:ml-6 lg:mt-6 lg:ml-0">
                    <h3 className="text-sm font-display font-medium tracking-tight text-white">{incentive.name}</h3>
                    <p className="mt-2 text-sm tracking-tight text-gray-300">{incentive.description}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>



      </Container>
    </section>
  )
}
